version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '3232:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  web:
    build: ./cliente
    ports:
      - "3000:3000"
    restart: always
    env_file: ./cliente/.env 
    environment:
      NODE_ENV: production
  api:
    build: ./server
    ports:
      - "4000:4000"
    restart: always
    env_file: ./server/.env
    links:
      - db
volumes:
  db:
    driver: local