export const FORMULARIO_AGREGAR_CLIENTE = "FORMULARIO_AGREGAR_CLIENTE";
export const CERRAR_AGREGAR_CLIENTE = "CERRAR_AGREGAR_CLIENTE";
export const OBTENER_CLIENTES = "OBTENER_CLIENTES";
export const AGREGAR_CLIENTE = "AGREGAR_CLIENTE";
export const MOSTRAR_ACTUALIZAR_CLIENTE = "MOSTRAR_ACTUALIZAR_CLIENTE";
export const ACTUALIZAR_CLIENTE = "ACTUALIZAR_CLIENTE";
export const ELIMINAR_CLIENTE = "ELIMINAR_CLIENTE";
export const OBTENER_CEDULA = "OBTENER_CEDULA";
