//Variables globales para el componente de alertas
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

//Variables globales para el componente de login
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const CERRAR_SESION = "CERRAR_SESION";

//Variables globales para el componente de Inicio
export const OBTENER_CAJA = "OBTENER_CAJA";
export const OBTENER_CLIENTES_TOTALES = "OBTENER_CLIENTES_TOTALES";
export const OBTENER_TOTAL_VENTA = "OBTENER_TOTAL_VENTA";
export const OBTENER_NUMERO_PRODUCTOS = "OBTENER_NUMERO_PRODUCTOS";

//Variables globales para el componente de clientes
export const FORMULARIO_AGREGAR_CLIENTE = "FORMULARIO_AGREGAR_CLIENTE";
export const CERRAR_AGREGAR_CLIENTE = "CERRAR_AGREGAR_CLIENTE";
export const OBTENER_CLIENTES = "OBTENER_CLIENTES";
export const AGREGAR_CLIENTE = "AGREGAR_CLIENTE";
export const MOSTRAR_ACTUALIZAR_CLIENTE = "MOSTRAR_ACTUALIZAR_CLIENTE";
export const ACTUALIZAR_CLIENTE = "ACTUALIZAR_CLIENTE";
export const OBTENER_DATOS_ACTUALIZAR = "OBTENER_DATOS_ACTUALIZAR";
export const ELIMINAR_CLIENTE = "ELIMINAR_CLIENTE";
export const OBTENER_CEDULA = "OBTENER_CEDULA";
export const CLIENTE_ERROR = "CLIENTE_ERROR";
export const BUSCAR = "BUSCAR";
export const OBTENER_BUSQUEDA = "OBTENER_BUSQUEDA";

//Variables globales para el componente de productos
export const OBTNER_PODUCTOS = "OBTNER_PODUCTOS";
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const OBTENER_CODIGO_PRODUCTO = "OBTENER_CODIGO_PRODUCTO";
export const OBTENER_PRODUCTO_ACTUALIZAR = "OBTENER_PRODUCTO_ACTUALIZAR";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const MOSTRAR_EDITAR_PRODUCTOS = "MOSTRAR_EDITAR_PRODUCTOS";
export const CERRAR_EDITAR_PRODUCTOS = "CERRAR_EDITAR_PRODUCTOS";
export const MOSTRAR_ACTUALIZAR_PRODUCTO = "MOSTRAR_ACTUALIZAR_PRODUCTO";
export const ACTUALIZAR_PRODUCTO = "ACTUALIZAR_PRODUCTO";

//Variables globales para el componente de ventas
export const OVTENER_PRODUCTOS_VEMTA = "OVTENER_PRODUCTOS_VEMTA";
export const MOSTRAR_DETALLE_VENTA = "MOSTRAR_DETALLE_VENTA";
export const CEDULA_CLIENTE = "CEDULA_CLIENTE";
export const ITEMS_DETALLE_VENTA = "ITEMS_DETALLE_VENTA";
export const MOSTRAR_INGRESAR_CLIENTE = "MOSTRAR_INGRESAR_CLIENTE";
export const CERRAR_INGRESAR_CLIENTE = "CERRAR_INGRESAR_CLIENTE";
export const CANCELAR_VENTA = "CANCELAR_VENTA";
export const ACTUALIZAR_DETALLE_VENTA = "ACTUALIZAR_DETALLE_VENTA";
export const ELIMINAR_ITEMS = "ELIMINAR_ITEMS";
export const VALORES_FACTURA = "VALORES_FACTURA";
export const OBTENER_NUMERO_ORDEN = "OBTENER_NUMERO_ORDEN";

//Variables globales para el componente de reporte
export const MOSTRAR_VISTA_REPORTE = "MOSTRAR_VISTA_REPORTE";
export const OBTENER_NUMERO_REPORTE = "OBTENER_NUMERO_REPORTE";
export const OCULTAR_VISTA_REPORTE = "OCULTAR_VISTA_REPORTE";
export const OBTENER_CADUCADOS = "OBTENER_CADUCADOS";
export const OBTENER_PRODUCTOS_ACABARSE = "OBTENER_PRODUCTOS_ACABARSE";
export const OBTENER_CLIENTES_CUMPLEANEROS = "OBTENER_CLIENTES_CUMPLEANEROS";
