export const FORMULARIO_AGREGAR_CLIENTE = "FORMULARIO_AGREGAR_CLIENTE";
export const CERRAR_AGREGAR_CLIENTE = "CERRAR_AGREGAR_CLIENTE";
export const OBTENER_CLIENTES = "OBTENER_CLIENTES";
export const AGREGAR_CLIENTE = "AGREGAR_CLIENTE";
